language: python

python:
  - "3.6"
  
before_install:
  - sudo apt-get install -y -q mpich libmpich-dev
  
install:
  - pip install pytest pytest-cov pytest-mock
  - pip install coveralls
  - pip install -r requirements.txt
  - cd bingocpp && ./build.sh && cd ..
  
before_script:
  - export PYTHONPATH=$PYTHONPATH:$PWD
  
script:
  - python -c "import bingo"
  - tests/run_tests.sh
  - python tests/performance_benchmarks.py
  - python tests/island_benchmarks.py

after_script:
  - coveralls
